### PR TITLE
Use NODE_ENV to pass build target

### PR DESCRIPTION
**Pull request by simon04**
This removes the dependency `minimist`.

### CODE REVIEW

**Comment by tomastrajan** [comment]
Would this work on all platforms? win, mac, linux ?

**Comment by simon04** [comment]
The documentation on `process.env` does not mention any incompatibilities: https://nodejs.org/docs/latest/api/process.html#process_process_env
The name `NODE_ENV` seems just to be a convention, see https://dzone.com/articles/what-you-should-know-about-node-env

**Comment by tomastrajan** [comment]
Sure I ment the way u used in npm `scripts` property... I am pretty sure that `NODE_ENV=DEV webpack-dev-server` will fail in windows console

**Comment by simon04** [comment]
Okay, I get you. https://www.npmjs.com/package/cross-env provides cross-platform environment variables. What about that?

**Comment by tomastrajan** [comment]
In that case we would be just swaping one dependency for another (`minimist` vs `cross-env`) and depending on som kind of implicit `crosn-env` magic versus just passing arguments explicitly. That being said, please let me know if you see some other advantages I may have missed.

**Comment by simon04** [comment]
Arguments in favor of `cross-env`:
* `webpack-dev-server@2.1.0-beta.12` fails with `Unknown argument: TARGET`.
* `cross-env` would solely be used in `package.json` and not being spread over `webpack.config.js` and `server.js`

**Comment by tomastrajan** [comment]
Ok, thank you these arguments make sense!

**Pull request merged**
